# Generated by Django 2.1.7 on 2019-04-14 21:00

import blog.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190414_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 21, 0, 25, 956787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 21, 0, 25, 956198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='personal-user-illustration-@2x.png', upload_to=blog.models.image_directory_path),
        ),
    ]
